name: ci-2384322252.164.1-config-options
'on':
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish release
        uses: >-
          eloquent/github-release-action@61d9c76739d368e0cb6286b65e273657696817ce
        with: {}
        id: publishRelease
      - name: Expose outputs
        env:
          PUBLISH_OPTIONS_OUTPUTS: ${{ toJSON(steps.publishRelease.outputs) }}
        run: echo ::notice title=Outputs::$PUBLISH_OPTIONS_OUTPUTS
