name: ci-2182238978.96.1-failure-lightweight
'on':
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish release
        uses: >-
          eloquent/github-release-action@66ad4e69667296be16b6b636bc0d26ae813b883f
