name: ci-manual.23kqradtte-success-draft
'on':
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish release
        uses: eloquent/github-release-action@main
        with:
          draft: true
